# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 675)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 675))
        MainWindow.setMaximumSize(QtCore.QSize(900, 675))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 671))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.info_layout = QtGui.QVBoxLayout()
        self.info_layout.setContentsMargins(11, 10, 10, 10)
        self.info_layout.setSpacing(5)
        self.info_layout.setObjectName(_fromUtf8("info_layout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_settings = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_settings.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_settings.setFrameShape(QtGui.QFrame.Box)
        self.label_settings.setObjectName(_fromUtf8("label_settings"))
        self.verticalLayout.addWidget(self.label_settings)
        self.label_select_mode = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_select_mode.setObjectName(_fromUtf8("label_select_mode"))
        self.verticalLayout.addWidget(self.label_select_mode)
        self.radio_mode_encoder = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radio_mode_encoder.setToolTip(_fromUtf8("Mode: DMTF encoder (play tones)"))
        self.radio_mode_encoder.setShortcut(_fromUtf8(""))
        self.radio_mode_encoder.setChecked(True)
        self.radio_mode_encoder.setObjectName(_fromUtf8("radio_mode_encoder"))
        self.verticalLayout.addWidget(self.radio_mode_encoder)
        self.radio_mode_decoder = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radio_mode_decoder.setToolTip(_fromUtf8("Mode: DMTF decoder (record tones)"))
        self.radio_mode_decoder.setStatusTip(_fromUtf8(""))
        self.radio_mode_decoder.setObjectName(_fromUtf8("radio_mode_decoder"))
        self.verticalLayout.addWidget(self.radio_mode_decoder)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.checkBox_saveDTMF_audio = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_saveDTMF_audio.setObjectName(_fromUtf8("checkBox_saveDTMF_audio"))
        self.verticalLayout.addWidget(self.checkBox_saveDTMF_audio)
        self.checkBox_saveDTMF_chart = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_saveDTMF_chart.setObjectName(_fromUtf8("checkBox_saveDTMF_chart"))
        self.verticalLayout.addWidget(self.checkBox_saveDTMF_chart)
        self.checkBox_saveDTMF_detected = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_saveDTMF_detected.setTristate(False)
        self.checkBox_saveDTMF_detected.setObjectName(_fromUtf8("checkBox_saveDTMF_detected"))
        self.verticalLayout.addWidget(self.checkBox_saveDTMF_detected)
        self.button_load_file_name = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.button_load_file_name.setObjectName(_fromUtf8("button_load_file_name"))
        self.verticalLayout.addWidget(self.button_load_file_name)
        self.loaded_file_name = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.loaded_file_name.setEnabled(False)
        self.loaded_file_name.setObjectName(_fromUtf8("loaded_file_name"))
        self.verticalLayout.addWidget(self.loaded_file_name)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button_record_mic = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.button_record_mic.setObjectName(_fromUtf8("button_record_mic"))
        self.verticalLayout.addWidget(self.button_record_mic)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dtmf_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.dtmf_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.dtmf_label.setFrameShape(QtGui.QFrame.Box)
        self.dtmf_label.setObjectName(_fromUtf8("dtmf_label"))
        self.verticalLayout_2.addWidget(self.dtmf_label)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dtmf_button_4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_4.sizePolicy().hasHeightForWidth())
        self.dtmf_button_4.setSizePolicy(sizePolicy)
        self.dtmf_button_4.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_4.setObjectName(_fromUtf8("dtmf_button_4"))
        self.gridLayout_2.addWidget(self.dtmf_button_4, 1, 1, 1, 1)
        self.dtmf_button_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_3.sizePolicy().hasHeightForWidth())
        self.dtmf_button_3.setSizePolicy(sizePolicy)
        self.dtmf_button_3.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_3.setObjectName(_fromUtf8("dtmf_button_3"))
        self.gridLayout_2.addWidget(self.dtmf_button_3, 0, 3, 1, 1)
        self.dtmf_button_0 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_0.sizePolicy().hasHeightForWidth())
        self.dtmf_button_0.setSizePolicy(sizePolicy)
        self.dtmf_button_0.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_0.setObjectName(_fromUtf8("dtmf_button_0"))
        self.gridLayout_2.addWidget(self.dtmf_button_0, 3, 2, 1, 1)
        self.dtmf_button_9 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_9.sizePolicy().hasHeightForWidth())
        self.dtmf_button_9.setSizePolicy(sizePolicy)
        self.dtmf_button_9.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_9.setObjectName(_fromUtf8("dtmf_button_9"))
        self.gridLayout_2.addWidget(self.dtmf_button_9, 2, 3, 1, 1)
        self.dtmf_button_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_2.sizePolicy().hasHeightForWidth())
        self.dtmf_button_2.setSizePolicy(sizePolicy)
        self.dtmf_button_2.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_2.setObjectName(_fromUtf8("dtmf_button_2"))
        self.gridLayout_2.addWidget(self.dtmf_button_2, 0, 2, 1, 1)
        self.dtmf_button_7 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_7.sizePolicy().hasHeightForWidth())
        self.dtmf_button_7.setSizePolicy(sizePolicy)
        self.dtmf_button_7.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_7.setObjectName(_fromUtf8("dtmf_button_7"))
        self.gridLayout_2.addWidget(self.dtmf_button_7, 2, 1, 1, 1)
        self.dtmf_button_8 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_8.sizePolicy().hasHeightForWidth())
        self.dtmf_button_8.setSizePolicy(sizePolicy)
        self.dtmf_button_8.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_8.setObjectName(_fromUtf8("dtmf_button_8"))
        self.gridLayout_2.addWidget(self.dtmf_button_8, 2, 2, 1, 1)
        self.dtmf_button_5 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_5.sizePolicy().hasHeightForWidth())
        self.dtmf_button_5.setSizePolicy(sizePolicy)
        self.dtmf_button_5.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_5.setObjectName(_fromUtf8("dtmf_button_5"))
        self.gridLayout_2.addWidget(self.dtmf_button_5, 1, 2, 1, 1)
        self.dtmf_button_1 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_1.sizePolicy().hasHeightForWidth())
        self.dtmf_button_1.setSizePolicy(sizePolicy)
        self.dtmf_button_1.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_1.setObjectName(_fromUtf8("dtmf_button_1"))
        self.gridLayout_2.addWidget(self.dtmf_button_1, 0, 1, 1, 1)
        self.dtmf_button_ast = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_ast.sizePolicy().hasHeightForWidth())
        self.dtmf_button_ast.setSizePolicy(sizePolicy)
        self.dtmf_button_ast.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_ast.setObjectName(_fromUtf8("dtmf_button_ast"))
        self.gridLayout_2.addWidget(self.dtmf_button_ast, 3, 1, 1, 1)
        self.dtmf_button_6 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_6.sizePolicy().hasHeightForWidth())
        self.dtmf_button_6.setSizePolicy(sizePolicy)
        self.dtmf_button_6.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_6.setObjectName(_fromUtf8("dtmf_button_6"))
        self.gridLayout_2.addWidget(self.dtmf_button_6, 1, 3, 1, 1)
        self.dtmf_button_hash = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtmf_button_hash.sizePolicy().hasHeightForWidth())
        self.dtmf_button_hash.setSizePolicy(sizePolicy)
        self.dtmf_button_hash.setStyleSheet(_fromUtf8("font: 75 14pt \"Consolas\";"))
        self.dtmf_button_hash.setObjectName(_fromUtf8("dtmf_button_hash"))
        self.gridLayout_2.addWidget(self.dtmf_button_hash, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.info_layout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.info_layout.addItem(spacerItem3)
        self.console_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.console_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.console_label.setFrameShape(QtGui.QFrame.Box)
        self.console_label.setObjectName(_fromUtf8("console_label"))
        self.info_layout.addWidget(self.console_label)
        self.console_display = QtGui.QListWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_display.sizePolicy().hasHeightForWidth())
        self.console_display.setSizePolicy(sizePolicy)
        self.console_display.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"font: 8pt \"Consolas\";\n"
"color: rgb(0, 255, 0);"))
        self.console_display.setFrameShape(QtGui.QFrame.NoFrame)
        self.console_display.setFrameShadow(QtGui.QFrame.Plain)
        self.console_display.setLineWidth(0)
        self.console_display.setAutoScrollMargin(50)
        self.console_display.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.console_display.setProperty("showDropIndicator", False)
        self.console_display.setAlternatingRowColors(False)
        self.console_display.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.console_display.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.console_display.setTextElideMode(QtCore.Qt.ElideNone)
        self.console_display.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.console_display.setFlow(QtGui.QListView.TopToBottom)
        self.console_display.setProperty("isWrapping", False)
        self.console_display.setResizeMode(QtGui.QListView.Adjust)
        self.console_display.setLayoutMode(QtGui.QListView.Batched)
        self.console_display.setViewMode(QtGui.QListView.ListMode)
        self.console_display.setModelColumn(0)
        self.console_display.setUniformItemSizes(True)
        self.console_display.setObjectName(_fromUtf8("console_display"))
        self.info_layout.addWidget(self.console_display)
        self.horizontalLayout.addLayout(self.info_layout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pbLevel = QtGui.QProgressBar(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLevel.sizePolicy().hasHeightForWidth())
        self.pbLevel.setSizePolicy(sizePolicy)
        self.pbLevel.setMaximum(1000)
        self.pbLevel.setProperty("value", 123)
        self.pbLevel.setTextVisible(False)
        self.pbLevel.setOrientation(QtCore.Qt.Vertical)
        self.pbLevel.setObjectName(_fromUtf8("pbLevel"))
        self.verticalLayout_4.addWidget(self.pbLevel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.plot_layout = QtGui.QVBoxLayout()
        self.plot_layout.setMargin(10)
        self.plot_layout.setSpacing(5)
        self.plot_layout.setObjectName(_fromUtf8("plot_layout"))
        self.label_realtime = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_realtime.sizePolicy().hasHeightForWidth())
        self.label_realtime.setSizePolicy(sizePolicy)
        self.label_realtime.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_realtime.setFrameShape(QtGui.QFrame.Box)
        self.label_realtime.setObjectName(_fromUtf8("label_realtime"))
        self.plot_layout.addWidget(self.label_realtime)
        self.widget_real_time_plot = PlotWidget(self.horizontalLayoutWidget)
        self.widget_real_time_plot.setObjectName(_fromUtf8("widget_real_time_plot"))
        self.plot_layout.addWidget(self.widget_real_time_plot)
        self.label_realtime_fourier = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_realtime_fourier.sizePolicy().hasHeightForWidth())
        self.label_realtime_fourier.setSizePolicy(sizePolicy)
        self.label_realtime_fourier.setMaximumSize(QtCore.QSize(600, 15))
        self.label_realtime_fourier.setFrameShape(QtGui.QFrame.Box)
        self.label_realtime_fourier.setObjectName(_fromUtf8("label_realtime_fourier"))
        self.plot_layout.addWidget(self.label_realtime_fourier)
        self.widget_fourier_plot = PlotWidget(self.horizontalLayoutWidget)
        self.widget_fourier_plot.setObjectName(_fromUtf8("widget_fourier_plot"))
        self.plot_layout.addWidget(self.widget_fourier_plot)
        self.horizontalLayout.addLayout(self.plot_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radio_mode_encoder, self.radio_mode_decoder)
        MainWindow.setTabOrder(self.radio_mode_decoder, self.dtmf_button_1)
        MainWindow.setTabOrder(self.dtmf_button_1, self.dtmf_button_2)
        MainWindow.setTabOrder(self.dtmf_button_2, self.dtmf_button_3)
        MainWindow.setTabOrder(self.dtmf_button_3, self.dtmf_button_4)
        MainWindow.setTabOrder(self.dtmf_button_4, self.dtmf_button_5)
        MainWindow.setTabOrder(self.dtmf_button_5, self.dtmf_button_6)
        MainWindow.setTabOrder(self.dtmf_button_6, self.dtmf_button_7)
        MainWindow.setTabOrder(self.dtmf_button_7, self.dtmf_button_8)
        MainWindow.setTabOrder(self.dtmf_button_8, self.dtmf_button_9)
        MainWindow.setTabOrder(self.dtmf_button_9, self.dtmf_button_ast)
        MainWindow.setTabOrder(self.dtmf_button_ast, self.dtmf_button_0)
        MainWindow.setTabOrder(self.dtmf_button_0, self.dtmf_button_hash)
        MainWindow.setTabOrder(self.dtmf_button_hash, self.button_load_file_name)
        MainWindow.setTabOrder(self.button_load_file_name, self.widget_real_time_plot)
        MainWindow.setTabOrder(self.widget_real_time_plot, self.widget_fourier_plot)
        MainWindow.setTabOrder(self.widget_fourier_plot, self.console_display)
        MainWindow.setTabOrder(self.console_display, self.loaded_file_name)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MPMF", None))
        self.label_settings.setText(_translate("MainWindow", "Settings", None))
        self.label_select_mode.setText(_translate("MainWindow", "Select Mode", None))
        self.radio_mode_encoder.setText(_translate("MainWindow", "Encoder", None))
        self.radio_mode_decoder.setText(_translate("MainWindow", "Decoder", None))
        self.checkBox_saveDTMF_audio.setText(_translate("MainWindow", "Save DTMF Tone Audio", None))
        self.checkBox_saveDTMF_chart.setText(_translate("MainWindow", "Save DTMF Tone Chart", None))
        self.checkBox_saveDTMF_detected.setText(_translate("MainWindow", "Save detected  DTMF Tone data", None))
        self.button_load_file_name.setText(_translate("MainWindow", "Load audio file", None))
        self.loaded_file_name.setPlaceholderText(_translate("MainWindow", "audio_file.wav", None))
        self.button_record_mic.setText(_translate("MainWindow", "Record Mic (1s)", None))
        self.dtmf_label.setText(_translate("MainWindow", "DTMF", None))
        self.dtmf_button_4.setText(_translate("MainWindow", "4", None))
        self.dtmf_button_3.setText(_translate("MainWindow", "3", None))
        self.dtmf_button_0.setText(_translate("MainWindow", "0", None))
        self.dtmf_button_9.setText(_translate("MainWindow", "9", None))
        self.dtmf_button_2.setText(_translate("MainWindow", "2", None))
        self.dtmf_button_7.setText(_translate("MainWindow", "7", None))
        self.dtmf_button_8.setText(_translate("MainWindow", "8", None))
        self.dtmf_button_5.setText(_translate("MainWindow", "5", None))
        self.dtmf_button_1.setText(_translate("MainWindow", "1", None))
        self.dtmf_button_ast.setText(_translate("MainWindow", "*", None))
        self.dtmf_button_6.setText(_translate("MainWindow", "6", None))
        self.dtmf_button_hash.setText(_translate("MainWindow", "#", None))
        self.console_label.setText(_translate("MainWindow", "Console", None))
        self.label_realtime.setToolTip(_translate("MainWindow", "Real time data from the source (mic or audio file)", None))
        self.label_realtime.setText(_translate("MainWindow", "Real Time Plot", None))
        self.label_realtime_fourier.setToolTip(_translate("MainWindow", "Fourier transform from data source above", None))
        self.label_realtime_fourier.setText(_translate("MainWindow", "Real Time Plot - Fourier", None))

from pyqtgraph import PlotWidget
