# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1200, 900)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans"))
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.bg_window = QtGui.QLabel(self.centralwidget)
        self.bg_window.setEnabled(True)
        self.bg_window.setGeometry(QtCore.QRect(0, 0, 1200, 900))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg_window.sizePolicy().hasHeightForWidth())
        self.bg_window.setSizePolicy(sizePolicy)
        self.bg_window.setMinimumSize(QtCore.QSize(1200, 900))
        self.bg_window.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans"))
        self.bg_window.setFont(font)
        self.bg_window.setText(_fromUtf8(""))
        self.bg_window.setPixmap(QtGui.QPixmap(_fromUtf8("src/img/mainwindow_bg.PNG")))
        self.bg_window.setObjectName(_fromUtf8("bg_window"))
        self.carrier_type_1 = QtGui.QComboBox(self.centralwidget)
        self.carrier_type_1.setGeometry(QtCore.QRect(300, 415, 114, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carrier_type_1.sizePolicy().hasHeightForWidth())
        self.carrier_type_1.setSizePolicy(sizePolicy)
        self.carrier_type_1.setObjectName(_fromUtf8("carrier_type_1"))
        self.carrier_type_1.addItem(_fromUtf8(""))
        self.carrier_type_1.addItem(_fromUtf8(""))
        self.spin_freq_1 = QtGui.QSpinBox(self.centralwidget)
        self.spin_freq_1.setGeometry(QtCore.QRect(425, 415, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_freq_1.sizePolicy().hasHeightForWidth())
        self.spin_freq_1.setSizePolicy(sizePolicy)
        self.spin_freq_1.setWrapping(False)
        self.spin_freq_1.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spin_freq_1.setSpecialValueText(_fromUtf8(""))
        self.spin_freq_1.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.spin_freq_1.setPrefix(_fromUtf8(""))
        self.spin_freq_1.setMaximum(15000)
        self.spin_freq_1.setSingleStep(100)
        self.spin_freq_1.setObjectName(_fromUtf8("spin_freq_1"))
        self.spin_freq_2 = QtGui.QSpinBox(self.centralwidget)
        self.spin_freq_2.setGeometry(QtCore.QRect(425, 865, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_freq_2.sizePolicy().hasHeightForWidth())
        self.spin_freq_2.setSizePolicy(sizePolicy)
        self.spin_freq_2.setMaximum(15000)
        self.spin_freq_2.setSingleStep(100)
        self.spin_freq_2.setObjectName(_fromUtf8("spin_freq_2"))
        self.carrier_type_2 = QtGui.QComboBox(self.centralwidget)
        self.carrier_type_2.setGeometry(QtCore.QRect(300, 865, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carrier_type_2.sizePolicy().hasHeightForWidth())
        self.carrier_type_2.setSizePolicy(sizePolicy)
        self.carrier_type_2.setObjectName(_fromUtf8("carrier_type_2"))
        self.carrier_type_2.addItem(_fromUtf8(""))
        self.carrier_type_2.addItem(_fromUtf8(""))
        self.button_record_1 = QtGui.QPushButton(self.centralwidget)
        self.button_record_1.setGeometry(QtCore.QRect(30, 415, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_record_1.sizePolicy().hasHeightForWidth())
        self.button_record_1.setSizePolicy(sizePolicy)
        self.button_record_1.setObjectName(_fromUtf8("button_record_1"))
        self.button_load_1 = QtGui.QPushButton(self.centralwidget)
        self.button_load_1.setGeometry(QtCore.QRect(155, 415, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_load_1.sizePolicy().hasHeightForWidth())
        self.button_load_1.setSizePolicy(sizePolicy)
        self.button_load_1.setObjectName(_fromUtf8("button_load_1"))
        self.button_record_2 = QtGui.QPushButton(self.centralwidget)
        self.button_record_2.setGeometry(QtCore.QRect(30, 865, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_record_2.sizePolicy().hasHeightForWidth())
        self.button_record_2.setSizePolicy(sizePolicy)
        self.button_record_2.setObjectName(_fromUtf8("button_record_2"))
        self.button_load_2 = QtGui.QPushButton(self.centralwidget)
        self.button_load_2.setGeometry(QtCore.QRect(155, 865, 115, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_load_2.sizePolicy().hasHeightForWidth())
        self.button_load_2.setSizePolicy(sizePolicy)
        self.button_load_2.setObjectName(_fromUtf8("button_load_2"))
        self.check_save_charts = QtGui.QCheckBox(self.centralwidget)
        self.check_save_charts.setGeometry(QtCore.QRect(830, 445, 110, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.check_save_charts.setFont(font)
        self.check_save_charts.setObjectName(_fromUtf8("check_save_charts"))
        self.check_save_audio = QtGui.QCheckBox(self.centralwidget)
        self.check_save_audio.setGeometry(QtCore.QRect(830, 465, 110, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.check_save_audio.setFont(font)
        self.check_save_audio.setObjectName(_fromUtf8("check_save_audio"))
        self.button_save = QtGui.QPushButton(self.centralwidget)
        self.button_save.setEnabled(True)
        self.button_save.setGeometry(QtCore.QRect(830, 415, 175, 25))
        self.button_save.setObjectName(_fromUtf8("button_save"))
        self.button_play = QtGui.QPushButton(self.centralwidget)
        self.button_play.setEnabled(True)
        self.button_play.setGeometry(QtCore.QRect(1015, 415, 175, 25))
        self.button_play.setObjectName(_fromUtf8("button_play"))
        self.check_save_charts_2 = QtGui.QCheckBox(self.centralwidget)
        self.check_save_charts_2.setGeometry(QtCore.QRect(1015, 445, 110, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.check_save_charts_2.setFont(font)
        self.check_save_charts_2.setObjectName(_fromUtf8("check_save_charts_2"))
        self.widget_audio1_time = PlotWidget(self.centralwidget)
        self.widget_audio1_time.setGeometry(QtCore.QRect(30, 35, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_audio1_time.sizePolicy().hasHeightForWidth())
        self.widget_audio1_time.setSizePolicy(sizePolicy)
        self.widget_audio1_time.setObjectName(_fromUtf8("widget_audio1_time"))
        self.widget_audio1_freq = PlotWidget(self.centralwidget)
        self.widget_audio1_freq.setGeometry(QtCore.QRect(30, 225, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_audio1_freq.sizePolicy().hasHeightForWidth())
        self.widget_audio1_freq.setSizePolicy(sizePolicy)
        self.widget_audio1_freq.setObjectName(_fromUtf8("widget_audio1_freq"))
        self.widget_audio2_time = PlotWidget(self.centralwidget)
        self.widget_audio2_time.setGeometry(QtCore.QRect(30, 485, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_audio2_time.sizePolicy().hasHeightForWidth())
        self.widget_audio2_time.setSizePolicy(sizePolicy)
        self.widget_audio2_time.setObjectName(_fromUtf8("widget_audio2_time"))
        self.widget_audio2_freq = PlotWidget(self.centralwidget)
        self.widget_audio2_freq.setGeometry(QtCore.QRect(30, 675, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_audio2_freq.sizePolicy().hasHeightForWidth())
        self.widget_audio2_freq.setSizePolicy(sizePolicy)
        self.widget_audio2_freq.setObjectName(_fromUtf8("widget_audio2_freq"))
        self.widget_carrier1_freq = PlotWidget(self.centralwidget)
        self.widget_carrier1_freq.setGeometry(QtCore.QRect(300, 225, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_carrier1_freq.sizePolicy().hasHeightForWidth())
        self.widget_carrier1_freq.setSizePolicy(sizePolicy)
        self.widget_carrier1_freq.setObjectName(_fromUtf8("widget_carrier1_freq"))
        self.widget_carrier2_time = PlotWidget(self.centralwidget)
        self.widget_carrier2_time.setGeometry(QtCore.QRect(300, 485, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_carrier2_time.sizePolicy().hasHeightForWidth())
        self.widget_carrier2_time.setSizePolicy(sizePolicy)
        self.widget_carrier2_time.setObjectName(_fromUtf8("widget_carrier2_time"))
        self.widget_carrier2_freq = PlotWidget(self.centralwidget)
        self.widget_carrier2_freq.setGeometry(QtCore.QRect(300, 675, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_carrier2_freq.sizePolicy().hasHeightForWidth())
        self.widget_carrier2_freq.setSizePolicy(sizePolicy)
        self.widget_carrier2_freq.setObjectName(_fromUtf8("widget_carrier2_freq"))
        self.widget_carrier1_time = PlotWidget(self.centralwidget)
        self.widget_carrier1_time.setGeometry(QtCore.QRect(300, 35, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_carrier1_time.sizePolicy().hasHeightForWidth())
        self.widget_carrier1_time.setSizePolicy(sizePolicy)
        self.widget_carrier1_time.setObjectName(_fromUtf8("widget_carrier1_time"))
        self.widget_modsig2_freq = PlotWidget(self.centralwidget)
        self.widget_modsig2_freq.setGeometry(QtCore.QRect(570, 675, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsig2_freq.sizePolicy().hasHeightForWidth())
        self.widget_modsig2_freq.setSizePolicy(sizePolicy)
        self.widget_modsig2_freq.setObjectName(_fromUtf8("widget_modsig2_freq"))
        self.widget_modsig2_time = PlotWidget(self.centralwidget)
        self.widget_modsig2_time.setGeometry(QtCore.QRect(570, 485, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsig2_time.sizePolicy().hasHeightForWidth())
        self.widget_modsig2_time.setSizePolicy(sizePolicy)
        self.widget_modsig2_time.setObjectName(_fromUtf8("widget_modsig2_time"))
        self.widget_modsig1_freq = PlotWidget(self.centralwidget)
        self.widget_modsig1_freq.setGeometry(QtCore.QRect(570, 225, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsig1_freq.sizePolicy().hasHeightForWidth())
        self.widget_modsig1_freq.setSizePolicy(sizePolicy)
        self.widget_modsig1_freq.setObjectName(_fromUtf8("widget_modsig1_freq"))
        self.widget_modsig1_time = PlotWidget(self.centralwidget)
        self.widget_modsig1_time.setGeometry(QtCore.QRect(570, 35, 240, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsig1_time.sizePolicy().hasHeightForWidth())
        self.widget_modsig1_time.setSizePolicy(sizePolicy)
        self.widget_modsig1_time.setObjectName(_fromUtf8("widget_modsig1_time"))
        self.widget_modsigf_time = PlotWidget(self.centralwidget)
        self.widget_modsigf_time.setGeometry(QtCore.QRect(830, 35, 360, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsigf_time.sizePolicy().hasHeightForWidth())
        self.widget_modsigf_time.setSizePolicy(sizePolicy)
        self.widget_modsigf_time.setObjectName(_fromUtf8("widget_modsigf_time"))
        self.widget_modsigf_freq = PlotWidget(self.centralwidget)
        self.widget_modsigf_freq.setGeometry(QtCore.QRect(830, 225, 360, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_modsigf_freq.sizePolicy().hasHeightForWidth())
        self.widget_modsigf_freq.setSizePolicy(sizePolicy)
        self.widget_modsigf_freq.setObjectName(_fromUtf8("widget_modsigf_freq"))
        self.console_display = QtGui.QListWidget(self.centralwidget)
        self.console_display.setGeometry(QtCore.QRect(830, 495, 360, 360))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_display.sizePolicy().hasHeightForWidth())
        self.console_display.setSizePolicy(sizePolicy)
        self.console_display.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"font: 8pt \"Consolas\";\n"
"color: rgb(0, 255, 0);"))
        self.console_display.setFrameShape(QtGui.QFrame.NoFrame)
        self.console_display.setFrameShadow(QtGui.QFrame.Plain)
        self.console_display.setLineWidth(0)
        self.console_display.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.console_display.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.console_display.setAutoScrollMargin(50)
        self.console_display.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.console_display.setProperty("showDropIndicator", False)
        self.console_display.setAlternatingRowColors(False)
        self.console_display.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.console_display.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.console_display.setTextElideMode(QtCore.Qt.ElideNone)
        self.console_display.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.console_display.setFlow(QtGui.QListView.TopToBottom)
        self.console_display.setProperty("isWrapping", False)
        self.console_display.setResizeMode(QtGui.QListView.Adjust)
        self.console_display.setLayoutMode(QtGui.QListView.Batched)
        self.console_display.setViewMode(QtGui.QListView.ListMode)
        self.console_display.setModelColumn(0)
        self.console_display.setUniformItemSizes(True)
        self.console_display.setObjectName(_fromUtf8("console_display"))
        self.link_to_docs = QtGui.QCommandLinkButton(self.centralwidget)
        self.link_to_docs.setGeometry(QtCore.QRect(950, 855, 285, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("src/img/doc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.link_to_docs.setIcon(icon)
        self.link_to_docs.setCheckable(False)
        self.link_to_docs.setObjectName(_fromUtf8("link_to_docs"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AM Modulator", None))
        self.carrier_type_1.setToolTip(_translate("MainWindow", "Choose the type of wave of the carrier", None))
        self.carrier_type_1.setItemText(0, _translate("MainWindow", "Cosine", None))
        self.carrier_type_1.setItemText(1, _translate("MainWindow", "Sine", None))
        self.spin_freq_1.setToolTip(_translate("MainWindow", "Choose the frequency of the Carrier", None))
        self.spin_freq_1.setSuffix(_translate("MainWindow", "Hz", None))
        self.spin_freq_2.setToolTip(_translate("MainWindow", "Choose the frequency of the Carrier", None))
        self.spin_freq_2.setSuffix(_translate("MainWindow", "Hz", None))
        self.carrier_type_2.setToolTip(_translate("MainWindow", "Choose the type of wave of the carrier", None))
        self.carrier_type_2.setItemText(0, _translate("MainWindow", "Cosine", None))
        self.carrier_type_2.setItemText(1, _translate("MainWindow", "Sine", None))
        self.button_record_1.setToolTip(_translate("MainWindow", "Record 5 seconds audio to transmit", None))
        self.button_record_1.setText(_translate("MainWindow", "Record Audio", None))
        self.button_load_1.setToolTip(_translate("MainWindow", "Load audio file from disk", None))
        self.button_load_1.setText(_translate("MainWindow", "Load Audio", None))
        self.button_record_2.setToolTip(_translate("MainWindow", "Record 5 seconds audio to transmit", None))
        self.button_record_2.setText(_translate("MainWindow", "Record Audio", None))
        self.button_load_2.setToolTip(_translate("MainWindow", "Load audio file from disk", None))
        self.button_load_2.setText(_translate("MainWindow", "Load Audio", None))
        self.check_save_charts.setText(_translate("MainWindow", "Save Charts", None))
        self.check_save_audio.setText(_translate("MainWindow", "Save Audios", None))
        self.button_save.setToolTip(_translate("MainWindow", "Save files", None))
        self.button_save.setText(_translate("MainWindow", "Save", None))
        self.button_play.setToolTip(_translate("MainWindow", "Reproduce resulting modulated signal", None))
        self.button_play.setText(_translate("MainWindow", "Play Signal", None))
        self.check_save_charts_2.setText(_translate("MainWindow", "Loop", None))
        self.link_to_docs.setToolTip(_translate("MainWindow", "Click to see documentation on GitHub", None))
        self.link_to_docs.setText(_translate("MainWindow", "Documentation", None))

from pyqtgraph import PlotWidget
